from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = ROOT / "data" / "processed" / "words" / "tem8_words_review_simple_corrected_draft.csv"
DEFAULT_OUTPUT = ROOT / "data" / "processed" / "words" / "tem8_words_llm_corrected_candidates.csv"
DEFAULT_APPROVED_ONLY = ROOT / "data" / "processed" / "words" / "tem8_words_llm_approved_only.csv"
DEFAULT_REJECTED_REVIEW = ROOT / "data" / "processed" / "words" / "tem8_words_llm_rejected_or_review.csv"


# These corrections are intentionally conservative: each item is accepted only when
# the Russian headword and the Chinese core meaning support the same standard word.
LLM_CORRECTIONS: dict[str, tuple[str, str, str]] = {
    "абаж": ("абажур", "approved", "lamp shade meaning and raw inflected form абажуром"),
    "абрикбс": ("абрикос", "approved", "apricot meaning"),
    "авантюрйист": ("авантюрист", "approved", "adventurer meaning"),
    "агитания": ("агитация", "approved", "propaganda meaning"),
    "агрессйвный": ("агрессивный", "approved", "aggressive meaning"),
    "алкоголйзм": ("алкоголизм", "approved", "alcoholism meaning"),
    "алкогбОлик": ("алкоголик", "approved", "alcoholic person meaning"),
    "анализйровать": ("анализировать", "approved", "analyze meaning"),
    "аналогйчный": ("аналогичный", "approved", "analogous meaning"),
    "ангйна": ("ангина", "approved", "tonsillitis meaning"),
    "армяЯнский": ("армянский", "approved", "Armenian adjective"),
    "артиллерййский": ("артиллерийский", "approved", "artillery adjective"),
    "астронбом": ("астроном", "approved", "astronomer meaning"),
    "атейст": ("атеист", "approved", "atheist meaning"),
    "балансйровать": ("балансировать", "approved", "balance meaning"),
    "балтйийский": ("балтийский", "approved", "Baltic meaning"),
    "баскетболйст": ("баскетболист", "approved", "basketball player meaning"),
    "безлйчный": ("безличный", "approved", "impersonal meaning"),
    "безразлйчный": ("безразличный", "approved", "indifferent meaning"),
    "беспартййный": ("беспартийный", "approved", "non-party meaning"),
    "беспокОЙйный": ("беспокойный", "approved", "restless/troublesome meaning"),
    "беспорЯдочный": ("беспорядочный", "approved", "disorderly meaning"),
    "бессйлие": ("бессилие", "approved", "weakness/powerlessness meaning"),
    "бесчйсленный": ("бесчисленный", "approved", "countless meaning"),
    "бетОнный": ("бетонный", "approved", "concrete adjective"),
    "бИОПОГЙчеСКИЙ": ("биологический", "approved", "biological meaning"),
    "блйжний": ("ближний", "approved", "nearby meaning"),
    "большевйтский": ("большевистский", "approved", "Bolshevik adjective"),
    "бойзнь": ("боязнь", "approved", "fear meaning"),
    "брестй": ("брести", "approved", "walk slowly meaning"),
    "бригадйр": ("бригадир", "approved", "brigade leader meaning"),
    "брйтва": ("бритва", "approved", "razor meaning"),
    "бродйить": ("бродить", "approved", "wander meaning"),
    "броОнзовый": ("бронзовый", "approved", "bronze meaning"),
    "бюрократйзм": ("бюрократизм", "approved", "bureaucratism meaning"),
    "валйть": ("валить", "approved", "fell/throw down meaning"),
    "валяЯться": ("валяться", "approved", "lie/roll about meaning"),
    "веройтность": ("вероятность", "approved", "probability meaning"),
    "весОмый": ("весомый", "approved", "weighty meaning"),
    "взЯтка": ("взятка", "approved", "bribe meaning"),
    "вйдИМЫй": ("видимый", "approved", "visible meaning"),
    "визйтка": ("визитка", "approved", "business card meaning"),
    "вйрус": ("вирус", "approved", "virus meaning"),
    "витамйн": ("витамин", "approved", "vitamin meaning"),
    "витрйна": ("витрина", "approved", "shop window meaning"),
    "ВИТЬ": ("вить", "approved", "twist/weave meaning"),
    "возйться": ("возиться", "approved", "busy oneself meaning"),
    "волейболйст": ("волейболист", "approved", "volleyball player meaning"),
    "ВОлЬНЫЙ": ("вольный", "approved", "free meaning"),
    "вселяЯть": ("вселять", "approved", "instill/move in meaning"),
    "вставлЯть": ("вставлять", "approved", "insert meaning"),
    "всходйть": ("всходить", "approved", "ascend/sprout meaning"),
    "ВЫЛИТЫый": ("вылитый", "approved", "exactly alike meaning"),
    "выноОсливость": ("выносливость", "approved", "endurance meaning"),
    "ВЫНОСЛИВЫЙ": ("выносливый", "approved", "enduring meaning"),
    "вЯлый": ("вялый", "approved", "withered/sluggish meaning"),
    "тармонйческий": ("гармонический", "approved", "harmonious meaning"),
    "гасйть": ("гасить", "approved", "extinguish meaning"),
    "гегемонйзм": ("гегемонизм", "approved", "hegemonism meaning"),
    "гйбкий": ("гибкий", "approved", "flexible meaning"),
    "хйбкость": ("гибкость", "approved", "flexibility meaning"),
    "ГИПсОоВЫй": ("гипсовый", "approved", "gypsum/plaster adjective"),
    "ГЛИНЯНЫЙ": ("глиняный", "approved", "clay adjective"),
    "говЯдина": ("говядина", "approved", "beef meaning"),
    "гонЯть": ("гонять", "approved", "drive/chase meaning"),
    "гонйться": ("гониться", "approved", "chase meaning"),
    "госпдОдство": ("господство", "approved", "domination meaning"),
    "грамматйический": ("грамматический", "approved", "grammatical meaning"),
    "гранйт": ("гранит", "approved", "granite meaning"),
    "гранйтный": ("гранитный", "approved", "granite adjective"),
    "грозйть": ("грозить", "approved", "threaten meaning"),
    "грузйть": ("грузить", "approved", "load meaning"),
    "губйть": ("губить", "approved", "ruin/destroy meaning"),
    "гулЯнье": ("гулянье", "approved", "festive walk/revelry meaning"),
    "дворянйн": ("дворянин", "approved", "nobleman meaning"),
    "двухсоОтый": ("двухсотый", "approved", "two-hundredth meaning"),
    "девйз": ("девиз", "approved", "motto meaning"),
    "девйца": ("девица", "approved", "girl/maiden meaning"),
    "девйчий": ("девичий", "approved", "maiden/girl adjective"),
    "демографйический": ("демографический", "approved", "demographic meaning"),
    "демократйзм": ("демократизм", "approved", "democratism meaning"),
    "детектйв": ("детектив", "approved", "detective story/movie meaning"),
    "дефицйт": ("дефицит", "approved", "deficit meaning"),
    "дефицйитный": ("дефицитный", "approved", "deficit/scarce adjective"),
    "джйнсы": ("джинсы", "approved", "jeans meaning"),
    "диалектиИческий": ("диалектический", "approved", "dialectical meaning"),
    "дйилер": ("дилер", "approved", "dealer meaning"),
    "динамйичный": ("динамичный", "approved", "dynamic meaning"),
    "директйва": ("директива", "approved", "directive meaning"),
    "дИспут": ("диспут", "approved", "academic debate meaning"),
    "дисциплинйрованный": ("дисциплинированный", "approved", "disciplined meaning"),
    "ДОЖДЛИВЫЙ": ("дождливый", "approved", "rainy meaning"),
    "дДОйТЬ": ("доить", "approved", "milk a cow meaning"),
    "ДОЛГ": ("долг", "approved", "duty/debt meaning"),
    "ДОЛЖНЫЙ": ("должный", "approved", "proper/due meaning"),
    "долйна": ("долина", "approved", "valley meaning"),
    "ДОНОСЙТЬ": ("доносить", "approved", "carry to/wear out meaning"),
    "донскоОйЙ": ("донской", "approved", "Don adjective"),
    "дорожйть": ("дорожить", "approved", "value/cherish meaning"),
    "дойрка": ("доярка", "approved", "milkmaid meaning"),
    "дразнйть": ("дразнить", "approved", "tease meaning"),
    "древесйна": ("древесина", "approved", "timber/wood meaning"),
    "душйть": ("душить", "approved", "strangle meaning"),
    "дуЭль": ("дуэль", "approved", "duel meaning"),
    "дуЭт": ("дуэт", "approved", "duet meaning"),
    "дьЯвол": ("дьявол", "approved", "devil meaning"),
    "Егйпет": ("Египет", "approved", "Egypt meaning"),
    "егйипетский": ("египетский", "approved", "Egyptian meaning"),
    "живопйсец": ("живописец", "approved", "painter meaning"),
    "ЖИвоПйсНЫйЙ": ("живописный", "approved", "picturesque/painting adjective"),
    "животноОводство": ("животноводство", "approved", "animal husbandry meaning"),
    "жйла": ("жила", "approved", "vein/tendon meaning"),
    "жилйще": ("жилище", "approved", "dwelling meaning"),
    "жилйщный": ("жилищный", "approved", "housing adjective"),
    "журналйистика": ("журналистика", "approved", "journalism meaning"),
    "загранйчный": ("заграничный", "approved", "foreign/abroad adjective"),
    "займствовать": ("заимствовать", "approved", "borrow/adopt meaning"),
    "закаляЯться": ("закаляться", "approved", "temper/harden meaning"),
    "закрепляЯть": ("закреплять", "approved", "fasten/consolidate meaning"),
    "залйв": ("залив", "approved", "bay/gulf meaning"),
    "лилй": ("лили", "needs_review", "could be verb form not headword"),
    "застОйный": ("застойный", "approved", "stagnant meaning"),
    "затЯгивать": ("затягивать", "approved", "tighten/delay meaning"),
    "ЗОЛОТйсТЫЙ": ("золотистый", "approved", "golden colour meaning"),
    "зубрйть": ("зубрить", "approved", "cram meaning"),
    "ЗзяТЬ": ("зять", "approved", "son-in-law meaning"),
    "идеалйзм": ("идеализм", "approved", "idealism meaning"),
    "изготовлЯтЬ": ("изготовлять", "approved", "make/manufacture meaning"),
    "изобйлие": ("изобилие", "approved", "abundance meaning"),
    "именйны": ("именины", "approved", "name day meaning"),
    "ймпорт": ("импорт", "approved", "import meaning"),
    "ймпортный": ("импортный", "approved", "import adjective"),
    "йИндекс": ("индекс", "approved", "index meaning"),
    "йней": ("иней", "approved", "hoarfrost meaning"),
    "интуйция": ("интуиция", "approved", "intuition meaning"),
    "конструйровать": ("конструировать", "approved", "design/construct meaning"),
    "Атлантический океан 大 西 洋": ("Атлантический океан", "approved", "Atlantic Ocean meaning"),
    "бытовбй": ("бытовой", "approved", "everyday/domestic adjective"),
    "высбОотный": ("высотный", "approved", "high-rise/high-altitude meaning"),
    "кого-что во что @ @ЕЛ #5 Р": ("", "rejected", "case government fragment"),
    "кого-что @Н #": ("", "rejected", "case government fragment"),
    "инвалйд": ("инвалид", "approved", "disabled person meaning"),
    "инвестйИция": ("инвестиция", "approved", "investment meaning"),
    "индйец": ("индиец", "approved", "Indian person meaning"),
    "Индййский океан 印 度 洋": ("Индийский океан", "approved", "Indian Ocean meaning"),
    "интернационалйизм": ("интернационализм", "approved", "internationalism meaning"),
    "инфинитйв": ("инфинитив", "approved", "infinitive meaning"),
    "иронйческий": ("иронический", "approved", "ironic meaning"),
    "исходйть": ("исходить", "approved", "come from/emanate meaning"),
    "исхОднЫый": ("исходный", "approved", "initial/source meaning"),
    "калйтка": ("калитка", "approved", "small gate meaning"),
    "капитулЯция": ("капитуляция", "approved", "capitulation meaning"),
    "картйнка * 66 -": ("картинка", "approved", "picture meaning"),
    "категорйический": ("категорический", "approved", "categorical meaning"),
    "катйить": ("катить", "approved", "roll/push meaning"),
    "католицйизм": ("католицизм", "approved", "Catholicism meaning"),
    "лй —# /разорвать книгу в клочкй 把 书 撕 成 碎 片": ("", "rejected", "example phrase fragment"),
    "кнйжка": ("книжка", "approved", "small book/booklet meaning"),
    "колйчественный": ("количественный", "approved", "quantitative meaning"),
    "коллектйвный": ("коллективный", "approved", "collective meaning"),
    "кОлокол": ("колокол", "approved", "bell meaning"),
    "колокоОльня": ("колокольня", "approved", "bell tower meaning"),
    "колорйт": ("колорит", "approved", "colouring/local colour meaning"),
    "комйиссия": ("комиссия", "approved", "commission meaning"),
    "композйция": ("композиция", "approved", "composition meaning"),
    "консерватйвный": ("консервативный", "approved", "conservative meaning"),
    "конструктйвный": ("конструктивный", "approved", "constructive meaning"),
    "конфлйкт": ("конфликт", "approved", "conflict meaning"),
    "кбОнчик": ("кончик", "approved", "tip/end meaning"),
    "копйровать": ("копировать", "approved", "copy meaning"),
    "копйть": ("копить", "approved", "save/accumulate meaning"),
    "корректйировать": ("корректировать", "approved", "correct/adjust meaning"),
    "косйть": ("косить", "approved", "mow meaning"),
    "коОсточка": ("косточка", "approved", "small bone/stone meaning"),
    "красноречйвый": ("красноречивый", "approved", "eloquent meaning"),
    "кредйт": ("кредит", "approved", "credit/loan meaning"),
    "крестйться": ("креститься", "approved", "be baptized/cross oneself meaning"),
    "крестьЯнский": ("крестьянский", "approved", "peasant adjective"),
    "крестьЯнство": ("крестьянство", "approved", "peasantry meaning"),
    "вавые глаза 充 血 的 眼 睛 @ЭМС НО": ("", "rejected", "example phrase fragment"),
    "кроссбОвки": ("кроссовки", "approved", "sneakers meaning"),
    "кружйть": ("кружить", "approved", "make rotate/circle meaning"),
    "кружйиться": ("кружиться", "approved", "spin/circle meaning"),
    "крутйть": ("крутить", "approved", "turn/twist meaning"),
    "крутйться": ("крутиться", "approved", "turn/spin meaning"),
    "кувшйн": ("кувшин", "approved", "jug meaning"),
    "кудряЯвый": ("кудрявый", "approved", "curly-haired meaning"),
    "культурйзм": ("культуризм", "approved", "bodybuilding meaning"),
    "кумйр": ("кумир", "approved", "idol meaning"),
    "лаконйчный": ("лаконичный", "approved", "concise meaning"),
    "ЭК": ("", "rejected", "proverb fragment"),
    "латвйийский": ("латвийский", "approved", "Latvian adjective"),
    "латИнский": ("латинский", "approved", "Latin adjective"),
    "лебедйный": ("лебединый", "approved", "swan adjective"),
    "ленинйзм": ("ленинизм", "approved", "Leninism meaning"),
    "лепйть": ("лепить", "approved", "sculpt/mould meaning"),
    "леснйк": ("лесник", "approved", "forester meaning"),
    "лечйть": ("лечить", "approved", "treat/cure meaning"),
    "либералйзм": ("либерализм", "approved", "liberalism meaning"),
    "лйвень": ("ливень", "approved", "downpour meaning"),
    "лйдер": ("лидер", "approved", "leader meaning"),
    "лидйровать": ("лидировать", "approved", "lead in competition meaning"),
    "лингвйст": ("лингвист", "approved", "linguist meaning"),
    "лингвйистика": ("лингвистика", "approved", "linguistics meaning"),
    "лОвкость": ("ловкость", "approved", "dexterity meaning"),
    "логйческий": ("логический", "approved", "logical meaning"),
    "ЛОГЙЧНЫЙ": ("логичный", "approved", "logical/reasonable meaning"),
    "локомотйв": ("локомотив", "approved", "locomotive meaning"),
    "лошадйный": ("лошадиный", "approved", "horse adjective"),
    "людскоОй": ("людской", "approved", "people's/human meaning"),
    "магнйт": ("магнит", "approved", "magnet meaning"),
    "мальчйшка": ("мальчишка", "approved", "boy meaning"),
    "мандарйн": ("мандарин", "approved", "mandarin orange meaning"),
    "манйть": ("манить", "approved", "beckon/attract meaning"),
    "массйв": ("массив", "approved", "massif/array meaning"),
    "материалйИзм": ("материализм", "approved", "materialism meaning"),
    "машинйстка": ("машинистка", "approved", "typist meaning"),
    "машйнка": ("машинка", "approved", "small machine meaning"),
    "машйнный": ("машинный", "approved", "machine adjective"),
    "местй": ("мести", "approved", "sweep meaning"),
    "металлургйческий": ("металлургический", "approved", "metallurgical meaning"),
    "метеорологйческий": ("метеорологический", "approved", "meteorological meaning"),
    "механйзм": ("механизм", "approved", "mechanism meaning"),
    "меховодй": ("меховой", "approved", "fur adjective"),
    "мещанйн": ("мещанин", "approved", "petty bourgeois/townsman meaning"),
    "мизйнен": ("мизинец", "approved", "little finger/toe meaning"),
    "милитарйизм": ("милитаризм", "approved", "militarism meaning"),
    "милйция": ("милиция", "approved", "police meaning"),
    "миллибннНый": ("миллионный", "approved", "millionth/million adjective"),
    "ЖОТ": ("", "rejected", "sentence fragment"),
    "миролюбйивый": ("миролюбивый", "approved", "peace-loving meaning"),
    "молйтва": ("молитва", "approved", "prayer meaning"),
    "молйТЬся": ("молиться", "approved", "pray meaning"),
    "молотйть": ("молотить", "approved", "thresh meaning"),
    "МОЛОЧНЫЙ": ("молочный", "approved", "milk adjective"),
    "морщйна": ("морщина", "approved", "wrinkle meaning"),
    "моршйнка": ("морщинка", "approved", "small wrinkle meaning"),
    "москоОвский": ("московский", "approved", "Moscow adjective"),
    "мотйв": ("мотив", "approved", "motive meaning"),
    "мОщность": ("мощность", "approved", "power/capacity meaning"),
    "мОЩНЫйЙ": ("мощный", "approved", "powerful meaning"),
    "мужйк": ("мужик", "approved", "peasant/man meaning"),
    "мяЯгкость": ("мягкость", "approved", "softness/gentleness meaning"),
    "наводйть": ("наводить", "approved", "direct/lead/bring about meaning"),
    "наглЯдный": ("наглядный", "approved", "visual/obvious meaning"),
    "налйчие": ("наличие", "approved", "presence/availability meaning"),
    "напйиться": ("напиться", "approved", "drink one's fill meaning"),
    "нарушйтель": ("нарушитель", "approved", "violator meaning"),
    "наряЯд": ("наряд", "approved", "attire/order detail meaning"),
    "насйлие": ("насилие", "approved", "violence meaning"),
    "настОльный": ("настольный", "approved", "table/desktop adjective"),
    "насторожйться": ("насторожиться", "approved", "become alert meaning"),
    "нахбОдчивый": ("находчивый", "approved", "resourceful meaning"),
    "националйизм": ("национализм", "approved", "nationalism meaning"),
    "нацйст": ("нацист", "approved", "Nazi meaning"),
    "небольшобй": ("небольшой", "approved", "small meaning"),
    "невйданный * 106 -": ("невиданный", "approved", "unprecedented meaning"),
    "невйдимый": ("невидимый", "approved", "invisible meaning"),
    "невозмОжный": ("невозможный", "approved", "impossible meaning"),
    "невОльный": ("невольный", "approved", "involuntary meaning"),
    "негрОмкий": ("негромкий", "approved", "not loud meaning"),
    "недвйжимость": ("недвижимость", "approved", "real estate meaning"),
    "недовОльный": ("недовольный", "approved", "dissatisfied meaning"),
    "неизмерймый": ("неизмеримый", "approved", "immeasurable meaning"),
    "некрасйвый": ("некрасивый", "approved", "ugly/not beautiful meaning"),
    "нелоОвкий": ("неловкий", "approved", "awkward meaning"),
    "неожйданность": ("неожиданность", "approved", "unexpected event meaning"),
    "неотлОожный": ("неотложный", "approved", "urgent meaning"),
    "непбОлный": ("неполный", "approved", "incomplete meaning"),
    "непримирйимый": ("непримиримый", "approved", "irreconcilable meaning"),
    "нерастворймый": ("нерастворимый", "approved", "insoluble meaning"),
    "нестйсь": ("нестись", "approved", "rush meaning"),
    "нетерпелйвый": ("нетерпеливый", "approved", "impatient meaning"),
    "неустОйчивый": ("неустойчивый", "approved", "unstable meaning"),
    "неутомймый": ("неутомимый", "approved", "tireless meaning"),
    "нефтЯник": ("нефтяник", "approved", "oil worker/specialist meaning"),
    "нехорОший": ("нехороший", "approved", "bad/not good meaning"),
    "новйнка": ("новинка", "approved", "novelty/new item meaning"),
    "нбОготЬ": ("ноготь", "approved", "fingernail/toenail meaning"),
    "носйлки": ("носилки", "approved", "stretcher meaning"),
    "носйтель": ("носитель", "approved", "carrier/representative meaning"),
    "НОСйТЬся": ("носиться", "approved", "rush about meaning"),
    "нЯня": ("няня", "approved", "nanny meaning"),
    "обвинЯть * 116 -": ("обвинять", "approved", "accuse meaning"),
    "обвинйЯть": ("обвинять", "approved", "accuse meaning"),
    "обйдный": ("обидный", "approved", "offensive/hurtful meaning"),
    "обйлие": ("обилие", "approved", "abundance meaning"),
    "обйильный": ("обильный", "approved", "abundant meaning"),
    "оборУдовать": ("оборудовать", "approved", "equip meaning"),
    "общйительный": ("общительный", "approved", "sociable meaning"),
    "объектйвность": ("объективность", "approved", "objectivity meaning"),
    "объектйвный": ("объективный", "approved", "objective meaning"),
    "ОВвсЯнНЫый": ("овсяный", "approved", "oat adjective"),
    "кого-что В 1": ("", "rejected", "case government fragment"),
    "торбнняя ткань 分 正 反 面 的 布 @ №1т К)": ("", "rejected", "phrase fragment"),
    "ОЗЙМЫЙ": ("озимый", "approved", "winter crop adjective"),
    "окОВЫ": ("оковы", "approved", "chains/shackles meaning"),
    "ОЛИМПИЙСКИЙ": ("олимпийский", "approved", "Olympic meaning"),
    "кого-что К&": ("", "rejected", "case government fragment"),
    "误 лННЕ": ("", "rejected", "OCR note fragment"),
    "определяЯться": ("определяться", "approved", "be defined/become clear meaning"),
    "органйческий": ("органический", "approved", "organic meaning"),
    "оскоОлок": ("осколок", "approved", "fragment/shard meaning"),
    "осложнятЬ": ("осложнять", "approved", "complicate meaning"),
    "ма-ленинйзма 马 克 思 列 宁 主 义 的 奠 基 人": ("", "rejected", "phrase fragment"),
    "отделЯть": ("отделять", "approved", "separate meaning"),
    "отлйичие": ("отличие", "approved", "difference meaning"),
    "отменЯть": ("отменять", "approved", "cancel/abolish meaning"),
    "относйтТЬ": ("относить", "approved", "carry away/relate meaning"),
    "естёственный водоём 天 然 水 体": ("естественный водоём", "approved", "natural body of water meaning"),
    "животноОводство": ("животноводство", "approved", "animal husbandry meaning"),
    "животновоОдство": ("животноводство", "approved", "animal husbandry meaning"),
    "иронйческий * 62 -": ("", "rejected", "meaning does not match ironic; likely page-header spillover"),
    "кефйир": ("кефир", "approved", "kefir meaning"),
    "лжйвЫый": ("лживый", "approved", "lying/deceitful meaning"),
    "лиходЙ": ("лихой", "approved", "dashing/evil/hard meaning"),
    "ОТЦОВсКИЙй": ("отцовский", "approved", "father's adjective"),
    "отчйизна": ("отчизна", "approved", "fatherland meaning"),
    "ОТЧчИй": ("отчий", "approved", "fatherly/paternal meaning"),
    "охбОтиться": ("охотиться", "approved", "hunt meaning"),
    "очевйдный": ("очевидный", "approved", "obvious meaning"),
    "очутйться": ("очутиться", "approved", "find oneself meaning"),
    "ощутймый": ("ощутимый", "approved", "perceptible meaning"),
    "пассйвный": ("пассивный", "approved", "passive meaning"),
    "патриотйзм": ("патриотизм", "approved", "patriotism meaning"),
    "патриотйческий": ("патриотический", "approved", "patriotic meaning"),
    "Пекйн": ("Пекин", "approved", "Beijing meaning"),
    "пекйнский": ("пекинский", "approved", "Beijing adjective"),
    "первйчный": ("первичный", "approved", "primary/initial meaning"),
    "перевозйть": ("перевозить", "approved", "transport across/by vehicle meaning"),
    "перевыполнятЬ": ("перевыполнять", "approved", "overfulfil meaning"),
    "передовйк": ("передовик", "approved", "advanced worker meaning"),
    "жйл": ("жил", "needs_review", "could be inflected form; not enough core meaning"),
    "перекусйть": ("перекусить", "approved", "bite through/have a snack meaning"),
    "перелйстывать": ("перелистывать", "approved", "leaf through meaning"),
    "перйла * 144 -": ("", "rejected", "meaning spillover does not match railing"),
    "перйла": ("перила", "approved", "railing meaning"),
    "периодйческий": ("периодический", "approved", "periodic meaning"),
    "периферйя": ("периферия", "approved", "periphery meaning"),
    "пианйст": ("пианист", "approved", "pianist meaning"),
    "ПИЛЙТЬ": ("пилить", "approved", "saw wood meaning"),
    "планйрование": ("планирование", "approved", "planning meaning"),
    "планйровать": ("планировать", "approved", "plan meaning"),
    "племЯнник": ("племянник", "approved", "nephew meaning"),
    "плестй": ("плести", "approved", "weave/invent meaning"),
    "плйтка": ("плитка", "approved", "tile/slab meaning"),
    "плотйна": ("плотина", "approved", "dam meaning"),
    "пляЯска": ("пляска", "approved", "dance meaning"),
    "повсФду . 150 .": ("повсюду", "approved", "everywhere meaning"),
    "повяЯзка": ("повязка", "approved", "bandage/armband meaning"),
    "погодйть": ("погодить", "approved", "wait a little meaning"),
    "погранйчник": ("пограничник", "approved", "border guard meaning"),
    "погуляЯть": ("погулять", "approved", "take a walk meaning"),
    "ПОДВЙЖНЫЙ": ("подвижный", "approved", "active/mobile meaning"),
    "подводИТЬ": ("подводить", "approved", "bring up/lead to meaning"),
    "подробсток": ("подросток", "approved", "teenager meaning"),
    "подрЯдный": ("подрядный", "approved", "contract adjective"),
    "поОдступ": ("подступ", "approved", "approach/access meaning"),
    "поженйться": ("пожениться", "approved", "get married meaning"),
    "155 . покбйник": ("", "rejected", "page-header spillover with wrong meaning"),
    "позабЫть": ("позабыть", "approved", "forget meaning"),
    "покОйник": ("покойник", "approved", "dead person meaning"),
    "покбйный * 156 -": ("покойный", "approved", "deceased meaning"),
    "полгдОда": ("полгода", "approved", "half a year meaning"),
    "полйтик": ("политик", "approved", "politician meaning"),
    "полномоОчный": ("полномочный", "approved", "plenipotentiary/authorized meaning"),
    "полбска * 158 -": ("полоска", "approved", "strip/column meaning"),
    "полбска": ("полоска", "approved", "strip meaning"),
    "полубстров": ("полуостров", "approved", "peninsula meaning"),
    "ПОПЛЫТЬ": ("поплыть", "approved", "start swimming/sailing meaning"),
    "ПОПОЛЗТЙ": ("поползти", "approved", "start crawling meaning"),
    "посбОльство": ("посольство", "approved", "embassy meaning"),
    "потребйтель": ("потребитель", "approved", "consumer meaning"),
    "потребйительский": ("потребительский", "approved", "consumer adjective"),
    "походйть2": ("походить", "approved", "walk for a while meaning"),
    "почйн": ("почин", "approved", "initiative meaning"),
    "поэтйческий": ("поэтический", "approved", "poetic meaning"),
    "поясняЯть": ("пояснять", "approved", "explain meaning"),
    "правйтель": ("правитель", "approved", "ruler meaning"),
    "правйтельственный ›": ("правительственный", "approved", "governmental meaning"),
    "практиИчный": ("практичный", "approved", "practical meaning"),
    "превосхОдный": ("превосходный", "approved", "excellent meaning"),
    "превосхоОдство": ("превосходство", "approved", "superiority meaning"),
    "предоставлЯться * 168 -": ("предоставляться", "approved", "be granted/given meaning"),
    "жёнием к раббте 对 工 作 采 取 轻 视 态 度 @ВНУ": ("", "rejected", "phrase fragment"),
    "пренебрежйтельный": ("пренебрежительный", "approved", "scornful/negligent meaning"),
    "престйж": ("престиж", "approved", "prestige meaning"),
    "престйжный": ("престижный", "approved", "prestigious meaning"),
    "приводйить": ("приводить", "approved", "bring/lead meaning"),
    "пригласйтельный": ("пригласительный", "approved", "invitation adjective"),
    "пригодйться": ("пригодиться", "approved", "be useful meaning"),
    "прилйчный": ("приличный", "approved", "decent/proper meaning"),
    "прйнтер": ("принтер", "approved", "printer meaning"),
    "проводйться": ("проводиться", "approved", "be conducted/held meaning"),
    "проводнйк": ("проводник", "approved", "conductor/guide meaning"),
    "проглотйть": ("проглотить", "approved", "swallow meaning"),
    "прогнозйст": ("прогнозист", "approved", "forecast specialist meaning"),
    "проговорйть": ("проговорить", "approved", "say/utter meaning"),
    "прогоняЯть": ("прогонять", "approved", "drive away meaning"),
    "пропйска": ("прописка", "approved", "residence registration meaning"),
    "прописнбй": ("прописной", "approved", "capital-letter adjective"),
    "простбй": ("простой", "approved", "downtime/simple meaning"),
    "протекционйзм": ("протекционизм", "approved", "protectionism/favouritism meaning"),
    "протйвный": ("противный", "approved", "opposite/contrary/nasty meaning"),
    "пройтйИсь": ("пройтись", "approved", "take a walk meaning"),
    "прямоугбОльник": ("прямоугольник", "approved", "rectangle meaning"),
    "психологйческий": ("психологический", "approved", "psychological meaning"),
    "ПТИЧИЙ": ("птичий", "approved", "bird adjective"),
    "публицистйческий": ("публицистический", "approved", "publicistic meaning"),
    "публйИчный": ("публичный", "approved", "public meaning"),
    "пушйстый": ("пушистый", "approved", "fluffy meaning"),
    "пшшенйичный": ("пшеничный", "approved", "wheat adjective"),
    "пылесбс": ("пылесос", "approved", "vacuum cleaner meaning"),
    "развитбй": ("развитой", "approved", "developed meaning"),
    "разводйиться": ("разводиться", "approved", "divorce/be bred meaning"),
    "разговорйться": ("разговориться", "approved", "begin talking freely meaning"),
    "разряЯд": ("разряд", "approved", "category/class meaning"),
    "расйзм": ("расизм", "approved", "racism meaning"),
    "расставляЯть": ("расставлять", "approved", "arrange/place meaning"),
    "реактйвный": ("реактивный", "approved", "reactive/jet meaning"),
    "197 . регулйровать": ("регулировать", "approved", "regulate meaning"),
    "реалйзм": ("реализм", "approved", "realism meaning"),
    "реалистйческий": ("реалистический", "approved", "realistic meaning"),
    "ребятйшки": ("ребятишки", "approved", "little children meaning"),
    "ревматйизм": ("ревматизм", "approved", "rheumatism meaning"),
    "регулйровать": ("регулировать", "approved", "regulate meaning"),
    "резйна": ("резина", "approved", "rubber meaning"),
    "резйнка": ("резинка", "approved", "eraser/rubber band meaning"),
    "резйновый": ("резиновый", "approved", "rubber adjective"),
    "ремонтйровать": ("ремонтировать", "approved", "repair meaning"),
    "реснйца": ("ресница", "approved", "eyelash meaning"),
    "решйимость": ("решимость", "approved", "determination meaning"),
    "рИмский": ("римский", "approved", "Roman meaning"),
    "роднйк": ("родник", "approved", "spring meaning"),
    "роскОшный": ("роскошный", "approved", "luxurious meaning"),
    "роОслый": ("рослый", "approved", "tall/stately meaning"),
    "россййский": ("российский", "approved", "Russian Federation adjective"),
    "Россйя": ("Россия", "approved", "Russia meaning"),
    "россиЯнин": ("россиянин", "approved", "Russian citizen meaning"),
    "рубйн": ("рубин", "approved", "ruby meaning"),
    "руднйк": ("рудник", "approved", "mine meaning"),
    "рукавйца": ("рукавица", "approved", "mitten meaning"),
    "руководЯщий": ("руководящий", "approved", "leading/managerial meaning"),
    "рулевбй": ("рулевой", "approved", "steering/rudder adjective"),
    "румяЯный": ("румяный", "approved", "rosy meaning"),
    "русйст": ("русист", "approved", "Russian philologist meaning"),
    "сатйра": ("сатира", "approved", "satire meaning"),
    "сатирйческий": ("сатирический", "approved", "satirical meaning"),
    "го-что @Н Н": ("", "rejected", "case government fragment"),
    "п сбылйсь": ("сбылись", "approved", "came true meaning"),
    "то-что @НГ": ("", "rejected", "case government fragment"),
    "светйло": ("светило", "approved", "luminary/celestial body meaning"),
    "свинйна": ("свинина", "approved", "pork meaning"),
    "свинцоОвый": ("свинцовый", "approved", "lead adjective"),
    "свободолюбйивый": ("свободолюбивый", "approved", "freedom-loving meaning"),
    "сводйть": ("сводить", "approved", "reduce/bring together meaning"),
    "сводйиться": ("сводиться", "approved", "be reduced to meaning"),
    "свелйсь": ("свелись", "approved", "were reduced to meaning"),
    "свОлочь": ("сволочь", "approved", "scoundrel meaning"),
    "свЯзка": ("связка", "approved", "bundle/link meaning"),
    "сезбОн": ("сезон", "approved", "season meaning"),
    "серебрйИстый": ("серебристый", "approved", "silvery meaning"),
    "серййный": ("серийный", "approved", "serial/batch adjective"),
    "сибйирский": ("сибирский", "approved", "Siberian meaning"),
    "силуЭт": ("силуэт", "approved", "silhouette meaning"),
    "символйческий": ("символический", "approved", "symbolic meaning"),
    "сйинтез": ("синтез", "approved", "synthesis meaning"),
    "систематйический": ("систематический", "approved", "systematic meaning"),
    "зйн-склад 仓 买 @& Ж": ("склад", "approved", "warehouse meaning"),
    "склОнность": ("склонность", "approved", "inclination/tendency meaning"),
    "склоняЯться": ("склоняться", "approved", "bend/decline meaning"),
    "СкОЛЬЗКИий": ("скользкий", "approved", "slippery meaning"),
    "скоплятЬ": ("скоплять", "approved", "accumulate meaning"),
    "славянйн": ("славянин", "approved", "Slav meaning"),
    "славЯнский": ("славянский", "approved", "Slavic meaning"),
    "СЛИВОЧчНЫЙ": ("сливочный", "approved", "cream adjective"),
    "сЛоМмйТЬ": ("сломить", "approved", "break/overcome meaning"),
    "п случгійность": ("случайность", "approved", "chance/accident meaning"),
    "снарЯд": ("снаряд", "approved", "shell/projectile meaning"),
    "снежйнка": ("снежинка", "approved", "snowflake meaning"),
    "п сносйть": ("сносить", "approved", "carry down/demolish meaning"),
    "солйст": ("солист", "approved", "soloist meaning"),
    "солйть": ("солить", "approved", "salt meaning"),
    "социал-демократйческий ›-ая": ("социал-демократический", "approved", "social-democratic meaning"),
    "спасйтельный": ("спасительный", "approved", "saving/rescuing meaning"),
    "спекулЯнт": ("спекулянт", "approved", "speculator meaning"),
    "225 . спокбйствие": ("спокойствие", "approved", "calmness meaning"),
    "спецйфика": ("специфика", "approved", "specificity meaning"),
    "специфйческий": ("специфический", "approved", "specific meaning"),
    "спйнка": ("спинка", "approved", "back of chair/sofa meaning"),
    "сплОШНой": ("сплошной", "approved", "continuous/solid meaning"),
    "спонсйировать": ("спонсировать", "approved", "sponsor meaning"),
    "кем-чем @ Н": ("", "rejected", "case government fragment"),
    "статйистика": ("статистика", "approved", "statistics meaning"),
    "статистйический": ("статистический", "approved", "statistical meaning"),
    "стеклЯнный": ("стеклянный", "approved", "glass adjective"),
    "стилйИстика": ("стилистика", "approved", "stylistics meaning"),
    "СТИХИЙНЫЙЙ": ("стихийный", "approved", "spontaneous/natural-force adjective"),
    "стихйя": ("стихия", "approved", "element/natural force meaning"),
    "СТОЙКИй": ("стойкий", "approved", "stable/resistant meaning"),
    "СТОЛЙЧНЫЙ": ("столичный", "approved", "capital-city adjective"),
    "столЯр": ("столяр", "approved", "carpenter meaning"),
    "стрбчка": ("строчка", "approved", "line of print meaning"),
    "стыдйТЬся": ("стыдиться", "approved", "be ashamed meaning"),
    "схОдный": ("сходный", "approved", "similar meaning"),
    "таджйкский": ("таджикский", "approved", "Tajik adjective"),
    "творйть": ("творить", "approved", "create meaning"),
    "творйиться": ("твориться", "approved", "happen/be created meaning"),
    "телохранйтель": ("телохранитель", "approved", "bodyguard meaning"),
    "теоретйческий": ("теоретический", "approved", "theoretical meaning"),
    "террорйзм": ("терроризм", "approved", "terrorism meaning"),
    "террорйст": ("террорист", "approved", "terrorist meaning"),
    "терЯться": ("теряться", "approved", "get lost/disappear meaning"),
    "тестйрование": ("тестирование", "approved", "testing meaning"),
    "Тихий океан 太 平 洋": ("Тихий океан", "approved", "Pacific Ocean meaning"),
    "ТОЛКОВЫЙ": ("толковый", "approved", "sensible/competent meaning"),
    "тормозйть": ("тормозить", "approved", "brake/hinder meaning"),
    "точйтЬ": ("точить", "approved", "sharpen meaning"),
    "ТОЩИЙ": ("тощий", "approved", "skinny meaning"),
    "транзйстор": ("транзистор", "approved", "transistor meaning"),
    "транслЯция": ("трансляция", "approved", "broadcast meaning"),
    "тропйческий": ("тропический", "approved", "tropical meaning"),
    "труслйвый": ("трусливый", "approved", "cowardly meaning"),
    "трЯпка": ("тряпка", "approved", "rag meaning"),
    "трястйись": ("трястись", "approved", "shake/tremble meaning"),
    "тупйк": ("тупик", "approved", "dead end meaning"),
    "тупбй": ("тупой", "approved", "blunt/dull meaning"),
    "турйстский": ("туристский", "approved", "tourist adjective"),
    "турнйр": ("турнир", "approved", "tournament meaning"),
    "убййца": ("убийца", "approved", "murderer meaning"),
    "убралйсь": ("убрались", "needs_review", "inflected plural form; consider lemma убраться"),
    "убйитый": ("убитый", "approved", "killed person/adjective meaning"),
    "уверяЯть": ("уверять", "approved", "assure meaning"),
    "уводйть": ("уводить", "approved", "lead away meaning"),
    "увозйть": ("увозить", "approved", "take away by vehicle meaning"),
    "утлублЯть": ("углублять", "approved", "deepen meaning"),
    "утлублЯться": ("углубляться", "approved", "deepen/go deeper meaning"),
    "утолбОвный": ("уголовный", "approved", "criminal-law adjective"),
    "уделяЯть": ("уделять", "approved", "devote/allot meaning"),
    "улйка": ("улика", "approved", "evidence/clue meaning"),
    "умоляЯть": ("умолять", "approved", "implore meaning"),
    "упбрство": ("упорство", "approved", "persistence meaning"),
    "уравнйловка": ("уравниловка", "approved", "levelling/equalizing policy meaning"),
    "урегулйровать": ("урегулировать", "approved", "settle/regulate meaning"),
    "УурОдливый": ("уродливый", "approved", "ugly/deformed meaning"),
    "усйдчивЫй": ("усидчивый", "approved", "diligent/persevering meaning"),
    "устрОйство": ("устройство", "approved", "device/arrangement meaning"),
    "утомйительный": ("утомительный", "approved", "tiring meaning"),
    "утопйИзм": ("утопизм", "approved", "utopianism meaning"),
    "уточняЯть": ("уточнять", "approved", "clarify/specify meaning"),
    "фальшйивый": ("фальшивый", "approved", "false/fake meaning"),
    "фантастйИческий": ("фантастический", "approved", "fantastic meaning"),
    "фашйстский": ("фашистский", "approved", "fascist adjective"),
    "физиологйческий": ("физиологический", "approved", "physiological meaning"),
    "фиксйровать › 254": ("фиксировать", "approved", "fix/register meaning"),
    "фиксйировать": ("фиксировать", "approved", "fix/register meaning"),
    "филологйческий": ("филологический", "approved", "philological meaning"),
    "финансйировать": ("финансировать", "approved", "finance meaning"),
    "формулйровать": ("формулировать", "approved", "formulate meaning"),
    "фразеологйческий": ("фразеологический", "approved", "phraseological meaning"),
    "футболйст": ("футболист", "approved", "football player meaning"),
    "хвалйиться": ("хвалиться", "approved", "boast meaning"),
    "хихйкать": ("хихикать", "approved", "giggle meaning"),
    "ХИЩНЫЙ": ("хищный", "approved", "predatory meaning"),
    "хромбй": ("хромой", "approved", "lame meaning"),
    "худобй": ("худой", "approved", "thin/bad meaning"),
    "царйзм": ("царизм", "approved", "tsarism meaning"),
    "цилйндр": ("цилиндр", "approved", "cylinder meaning"),
    "черновйк": ("черновик", "approved", "draft meaning"),
    "чертйитЬ": ("чертить", "approved", "draw/draft meaning"),
    "ЧИН": ("чин", "approved", "rank meaning"),
    "чйасы": ("чипсы", "approved", "potato chips meaning"),
    "шахматйст": ("шахматист", "approved", "chess player meaning"),
    "шевелйть": ("шевелить", "approved", "move/stir meaning"),
    "шевелйться": ("шевелиться", "approved", "move/stir meaning"),
    "шовинйзм": ("шовинизм", "approved", "chauvinism meaning"),
    "шутлйвый": ("шутливый", "approved", "joking/playful meaning"),
    "щадйть": ("щадить", "approved", "spare meaning"),
    "ться из Москвы 撒 离 莫 斯 科": ("", "rejected", "phrase fragment"),
    "экологйческий": ("экологический", "approved", "ecological meaning"),
    "экономйст": ("экономист", "approved", "economist meaning"),
    "экондОмный": ("экономный", "approved", "economical meaning"),
    "экспозйнпия": ("экспозиция", "approved", "exposition/display meaning"),
    "эрудйт": ("эрудит", "approved", "erudite person meaning"),
    "эстОнский": ("эстонский", "approved", "Estonian adjective"),
    "эфйир": ("эфир", "approved", "ether/airwaves meaning"),
    "эффектйИвность": ("эффективность", "approved", "effectiveness meaning"),
    "эффектйвный": ("эффективный", "approved", "effective meaning"),
    "ЯДОВЙИТЫЙ": ("ядовитый", "approved", "poisonous meaning"),
    "И Москва не сразу стрбилась. 莫 斯 科 不 是 一 日 建 成 的": ("", "rejected", "proverb sentence fragment"),
    "Из икры возгорйтся пламя. 星 星 之 火 可 以 燎 原 。": ("", "rejected", "proverb sentence fragment"),
    "неприяйтный": ("неприятный", "approved", "unpleasant meaning"),
    "нерешийтельный": ("нерешительный", "approved", "indecisive meaning"),
    "покбойный": ("покойный", "approved", "deceased meaning"),
    "пострбойка": ("постройка", "approved", "building meaning"),
    "прозайческий": ("прозаический", "approved", "prosaic meaning"),
    "реконструйровать": ("реконструировать", "approved", "reconstruct meaning"),
    "спокбойствие": ("спокойствие", "approved", "calmness meaning"),
    "термойдерный": ("термоядерный", "approved", "thermonuclear meaning"),
    "Украйна": ("Украина", "approved", "Ukraine meaning"),
    "устойть": ("устоять", "approved", "stand firm meaning"),
    "хоккейст": ("хоккеист", "approved", "hockey player meaning"),
    "тийшка": ("шишка", "approved", "cone meaning"),
    "эвакуйровать": ("эвакуировать", "approved", "evacuate meaning"),
    "эгойзм": ("эгоизм", "approved", "egoism meaning"),
    "естёственныйводоём": ("естественный водоём", "approved", "natural body of water phrase"),
    "нейсныемысли": ("", "rejected", "phrase fragment and corrupted headword"),
    "пльскийспрос": ("", "rejected", "phrase fragment and corrupted headword"),
    "ЖЖ": ("", "rejected", "sentence fragment, not a headword"),
    "тьй": ("", "rejected", "fragment not recoverable as a headword"),
    "шб": ("", "rejected", "proverb fragment, not a headword"),
    "наякартйна": ("", "rejected", "phrase fragment from загадочная картина/expression"),
    "шльныйистбчник": ("", "rejected", "phrase fragment from минеральный источник"),
    "видудельныеосббенности-индивидуальныйстильЛКинди-": ("", "rejected", "long phrase fragment, not a headword"),
    "льно-освободительноедвижение": ("", "rejected", "phrase fragment from национально-освободительное движение"),
    "Подббномблнииегбпронзиластрашнаямысль": ("", "rejected", "sentence fragment"),
    "ЯТНпродбльноеипоперечноесечение": ("", "rejected", "phrase fragment"),
    "НЫоЛОНОЙрылеть": ("", "rejected", "phrase fragment"),
    "МынахбдимсяподохранойКрасногоКреста": ("", "rejected", "sentence fragment"),
    "тыйслогУдарениепедаетнапервыйслог": ("", "rejected", "sentence fragment"),
    "узнатьширбкиеслойраббчихТККТЛВЕсоциальныйслой": ("", "rejected", "phrase fragment"),
    "Большбмукораблю-большбеплавание": ("", "rejected", "proverb fragment"),
}


def normalize(value: str) -> str:
    return (value or "").strip()


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as stream:
        return list(csv.DictReader(stream))


def write_csv(path: Path, rows: list[dict[str, str]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8-sig", newline="") as stream:
        writer = csv.DictWriter(stream, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def build_rows(rows: list[dict[str, str]]) -> list[dict[str, str]]:
    corrected_rows: list[dict[str, str]] = []
    for row in rows:
        original = normalize(row.get("original_word", "")) or normalize(row.get("word", ""))
        current = normalize(row.get("word", ""))
        decision = LLM_CORRECTIONS.get(original) or LLM_CORRECTIONS.get(current)
        out = dict(row)
        out["llm_original_word"] = original
        out["llm_suggested_word"] = ""
        out["llm_review_status"] = "not_checked"
        out["llm_notes"] = ""
        if decision:
            suggested, status, notes = decision
            out["llm_suggested_word"] = suggested
            out["llm_review_status"] = f"llm_{status}"
            out["llm_notes"] = notes
            if status == "approved":
                out["word"] = suggested
                out["review_status"] = "pending"
                out["review_notes"] = "llm_suggested_approved_requires_user_review"
            elif status == "rejected":
                out["review_status"] = "rejected_suggestion"
                out["review_notes"] = "llm_rejected_corrupt_or_phrase_fragment"
            else:
                out["review_status"] = "needs_review"
                out["review_notes"] = "llm_needs_review"
        corrected_rows.append(out)
    return corrected_rows


def summarize(rows: list[dict[str, str]]) -> dict[str, object]:
    counts: dict[str, int] = {}
    for row in rows:
        status = row.get("llm_review_status", "not_checked")
        counts[status] = counts.get(status, 0) + 1
    return {
        "rows": len(rows),
        "llm_status": counts,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Build a conservative LLM-assisted vocabulary correction sheet.")
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--approved-only", type=Path, default=DEFAULT_APPROVED_ONLY)
    parser.add_argument("--rejected-review", type=Path, default=DEFAULT_REJECTED_REVIEW)
    args = parser.parse_args()

    rows = read_csv(args.input)
    corrected = build_rows(rows)
    extra_fields = ["llm_original_word", "llm_suggested_word", "llm_review_status", "llm_notes"]
    fieldnames = [*rows[0].keys(), *extra_fields] if rows else extra_fields
    write_csv(args.output, corrected, fieldnames)
    approved_only = [row for row in corrected if row.get("llm_review_status") == "llm_approved"]
    rejected_review = [
        row
        for row in corrected
        if row.get("llm_review_status") in {"llm_rejected", "llm_needs_review"}
    ]
    write_csv(args.approved_only, approved_only, fieldnames)
    write_csv(args.rejected_review, rejected_review, fieldnames)
    summary = summarize(corrected)
    summary["output"] = str(args.output)
    summary["approved_only"] = str(args.approved_only)
    summary["rejected_review"] = str(args.rejected_review)
    print(json.dumps(summary, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
